language: generic

services: 
    - docker

before_install:
    - docker build -t tjgytmd007/react_test_app -f ./frontend/Dockerfile.dev ./frontend

script:
    - docker run -e CI=true tjgytmd007/react-test-app npm run test

after_success:
    - docker build -t tjgytmd007/docker-frontend ./frontend
    - docker build -t tjgytmd007/docker-backend ./backend
    - docker build -t tjgytmd007/docker-nginx ./nginx

    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "DOCKER_HUB_ID" --password-stdin

    - docker push tjgytmd007/docker-frontend
    - docker push tjgytmd007/docker-backend
    - docker push tjgytmd007/docker-nginx

